# Eureka server configuration
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
server.port=8761
spring.application.name=eureka-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

#eureka.server.eviction-interval-timer-in-ms=10000
eureka.server.renewal-percent-threshold=0.85
eureka.server.renewal-threshold-update-interval-ms=15000

