spring.application.name=attendance-service
spring.config.import=optional:configserver:http://localhost:8888
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
spring.cloud.client.hostname=localhost
